### ISSUE TITLE
Arduino UNO: Only 0 value

### ISSUE THREAD

**Issue by jonathanrjpereira** [FryDay/MPU-9250#1]
```
Roll: 0  Pitch: 0
Roll: 0  Pitch: 0

```
Can you provide the correct wiring diagram

**Comment by hardymunjal** [comment]
![documents - shortcut](https://user-images.githubusercontent.com/25545652/28742461-594eb9ca-744e-11e7-8a65-0f8bb525ece4.png)

**Comment by FryDay** [comment]
@jonathanrjpereira, @hardy8059 is correct. The library uses I2C to communicate with the MPU-9250, so you should be getting results by connecting SDA to A4 and SCL to A5. Also make sure you are not connecting the MPU-9250 to 5v or you will burn it out.
